# fly.toml app configuration file generated for nus-fotobook on 2023-07-25T13:47:52+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nus-fotobook"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[deploy]
  release_command = "./bin/rails db:prepare"

swap_size_mb = 1024
